image: gcc:8

build:
  stage: build
  before_script:
    - >
      apt update &&
      apt -y install
      gcc-mingw-w64 g++-mingw-w64 cmake make
      libavformat-dev libavcodec-dev libswscale-dev
  script:
    - mkdir -p build
    - cd build
    - cmake -D CMAKE_TOOLCHAIN_FILE=../CMake-MingWcross-toolchain.txt ..
    - make
  artifacts:
    paths:
      - build/vis_avs.dll
  cache:
    paths:
      - "build/"
