image: gcc:9

build:
  stage: build
  before_script:
    - .ci/tasks.sh install-deps ubuntu
  script:
    - .ci/tasks.sh build-win32
    - .ci/tasks.sh build-linux32
  artifacts:
    paths:
      - build_win32/vis_avs.dll
      - build_win32/libavs.dll
      - build_linux32/libavs.so
  cache:
    paths:
      - "build_win32/"
      - "build_linux32/"
